"""Cross-language control vectors: Python-built canonical bytes and signatures.

``deploy/cloudflare/worker/test/fixtures/control-vectors.json`` is generated
by ``build()`` and checked by both languages: the Python test rebuilds it and
requires equality, the TypeScript test recomputes canonicalBytes and verifies
every signature with verifyControl. The key is a fixture key derived from a
label; it authorizes nothing.
"""

from __future__ import annotations

import base64
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path

from release_cloudflare.control_client import ControlCommand, body_bytes, canonical_bytes

FIXTURE = (
    Path(__file__).resolve().parents[1]
    / "deploy/cloudflare/worker/test/fixtures/control-vectors.json"
)
SEED = hashlib.sha256(b"sentry fixture control key; authorizes nothing").digest()
RELEASE = "0b9f7c1e-4d2a-4f6b-9a3e-2c1d0e9f8a7b"
CASES = [
    ("POST", "worker/worker-0", "start", {"release_id": RELEASE}, "start-worker-" + RELEASE),
    ("POST", "api/api-0", "stop", {"start_nonce": "a" * 32}, "stop-" + "a" * 32),
    ("GET", "runtime/runtime-0", "status", None, "read-" + "1" * 32),
    ("POST", f"jobs/job-{RELEASE}-runtime-grant", "run",
     {"job_id": "runtime-grant", "phase": "grant", "database": "runtime",
      "image": "release_tools", "deadline_seconds": 900}, "tok-0000000000000001"),
    ("POST", "worker/worker-0", "receipts", {"start_nonce": "b" * 32, "after": 7, "limit": 100},
     "read-" + "2" * 32),
]  # fmt: skip


def private_key():
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    return Ed25519PrivateKey.from_private_bytes(SEED)


def build() -> dict:
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    key = private_key()
    public = key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
    vectors = []
    for index, (method, target, action, body, command_id) in enumerate(CASES):
        payload = body_bytes(body)
        command = ControlCommand(
            method=method,
            target=target,
            action=action,
            body_sha256=hashlib.sha256(payload).hexdigest(),
            release_id=RELEASE,
            session="session-a",
            fence=str(index + 1),
            command_id=command_id,
            expires_at=1_800_000_060 + index,
        )
        canonical = canonical_bytes(command)
        vectors.append(
            {
                "command": {
                    "method": command.method,
                    "target": command.target,
                    "action": command.action,
                    "bodySha256": command.body_sha256,
                    "releaseId": command.release_id,
                    "session": command.session,
                    "fence": command.fence,
                    "commandId": command.command_id,
                    "expiresAt": command.expires_at,
                },
                "body": payload.decode("utf-8"),
                # The journaled command_expires_at this expiry is signed from.
                "expiresIso": datetime.fromtimestamp(command.expires_at, timezone.utc).strftime(
                    "%Y-%m-%dT%H:%M:%SZ"
                ),
                "canonical": base64.b64encode(canonical).decode("ascii"),
                "signature": base64.b64encode(key.sign(canonical)).decode("ascii"),
            }
        )
    return {
        "note": "Generated by tests/cloudflare_control_vectors.py; fixture key, authorizes nothing.",
        "publicKey": base64.b64encode(public).decode("ascii"),
        "now": 1_800_000_000,
        "vectors": vectors,
    }


if __name__ == "__main__":
    FIXTURE.write_text(json.dumps(build(), indent=2) + "\n")
