import type { ReportDetail } from './api-contracts';

export const SAMPLE_REPORT: ReportDetail = {
  id: 'public-sample-cobalt-strike',
  tool_name: 'Cobalt Strike',
  category: 'malware',
  threat_type: 'post_exploitation_framework',
  classification_status: 'recorded',
  claim_attribution_status: 'attributed',
  claim_attribution_version: '2',
  quality_score: 3.5,
  created_at: '2026-08-13T12:00:00.000Z',
  processing_time_ms: 0,
  status: 'completed',
  generation_stage: 'completed',
  evaluation_status: 'completed',
  evaluation_attempts: 1,
  evaluated_at: '2026-08-13T12:03:00.000Z',
  review_status: 'reviewable',
  analyst_disposition: 'unreviewed',
  current_disposition: null,
  disposition_history: [],
  quality_assessment: {
    overall_score: 3.5,
    needs_improvement: false,
    critical_issues: [],
    summary: { passed_sections: 7, failed_sections: 0, unavailable_sections: 0 },
    consistency: { consistency_score: 4.0, inconsistencies: [], recommendations: [] },
  },
  content_preview: 'An acceptable profile of Cobalt Strike capabilities, observed abuse, and detection priorities.',
  markdown_content: [
    '# Cobalt Strike',
    '',
    '## Executive Summary',
    '',
    'Cobalt Strike is a commercial adversary-simulation platform whose Beacon payload supports post-exploitation activity. The [official product documentation](https://www.cobaltstrike.com/product) describes its command-and-control and extensibility features; [MITRE ATT&CK](https://attack.mitre.org/software/S0154/) catalogs the software as S0154 and maps observed techniques.',
    '',
    'Defenders should treat the presence of an unauthorized Beacon as high-priority evidence while preserving the distinction between legitimate assessment use and malicious deployment.',
    '',
    '## Profile Metadata',
    '',
    '| Field | Value |',
    '| --- | --- |',
    '| Category | Post-exploitation framework |',
    '| Classification | Dual-use software |',
    '| ATT&CK software ID | S0154 |',
    '| Review posture | Acceptable |',
    '',
    '## Capabilities and Observed Use',
    '',
    '- Beacon supports command execution, file transfer, and configurable command-and-control behavior.',
    '- Operators can adapt traffic profiles and extend workflows for an engagement.',
    '- [CISA reporting](https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-187a) documents threat actors using Cobalt Strike Beacons for persistence, credential access, lateral movement, and data exfiltration in a wider intrusion chain.',
    '',
    '## Forensic Artifacts',
    '',
    'A memory-resident Beacon payload inside an injected process is a forensic artifact analysts can preserve and investigate.',
    '',
    '## Detection Guidance',
    '',
    'Correlate endpoint and network evidence rather than relying on a single signature:',
    '',
    '1. Investigate process injection and memory-resident payload behavior.',
    '2. Hunt for periodic callbacks to low-reputation infrastructure, accounting for sleep and jitter.',
    '3. Review credential-access and lateral-movement activity that follows an initial Beacon alert.',
    '',
    '```sigma',
    'title: Suspicious Beacon Follow-on Activity',
    'status: experimental',
    'logsource:',
    '  category: process_creation',
    '  product: windows',
    'detection:',
    '  selection:',
    '    ParentImage|endswith: "\\\\rundll32.exe"',
    '    Image|endswith: "\\\\powershell.exe"',
    '  condition: selection',
    '```',
    '',
    '## Mitigation Priorities',
    '',
    '- Restrict unnecessary outbound traffic and monitor long-lived HTTP, HTTPS, and DNS sessions.',
    '- Enforce least privilege and application control to limit payload execution and lateral movement.',
    '- Preserve endpoint telemetry needed to connect injection, credential access, and command-and-control activity.',
    '',
    '> This sample demonstrates the report format. Analysts should validate each finding against current evidence before operational use.',
  ].join('\n'),
  web_sources: [
    {
      source_id: 'S1',
      title: 'Cobalt Strike product documentation',
      url: 'https://www.cobaltstrike.com/product',
      domain: 'cobaltstrike.com',
      access_date: '2026-08-13',
      relevance_score: '0.98',
      content_type: 'Vendor documentation',
      key_findings: 'Describes Beacon, command-and-control customization, and post-exploitation capabilities.',
    },
    {
      source_id: 'S2',
      title: 'MITRE ATT&CK: Cobalt Strike (S0154)',
      url: 'https://attack.mitre.org/software/S0154/',
      domain: 'attack.mitre.org',
      access_date: '2026-08-13',
      relevance_score: '0.99',
      content_type: 'Threat knowledge base',
      key_findings: 'Maps Cobalt Strike to observed adversary techniques and public reporting.',
    },
    {
      source_id: 'S3',
      title: 'CISA: Increased Truebot Activity',
      url: 'https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-187a',
      domain: 'cisa.gov',
      access_date: '2026-08-13',
      relevance_score: '0.91',
      content_type: 'Government advisory',
      key_findings: 'Documents malicious Beacon use for persistence, credential access, lateral movement, and exfiltration.',
    },
  ],
  claim_attributions: [
    {
      claim_class: 'threat_activity',
      claim: 'documents threat actors using Cobalt Strike Beacons for persistence, credential access, lateral movement, and data exfiltration in a wider intrusion chain.',
      source_ids: ['S3'],
    },
    {
      claim_class: 'forensic_artifact',
      claim: 'A memory-resident Beacon payload inside an injected process is a forensic artifact analysts can preserve and investigate.',
      source_ids: ['S2'],
    },
    {
      claim_class: 'detection_indicator',
      claim: 'Hunt for periodic callbacks to low-reputation infrastructure, accounting for sleep and jitter.',
      source_ids: ['S1', 'S2'],
    },
    {
      claim_class: 'mitigation_action',
      claim: 'Enforce least privilege and application control to limit payload execution and lateral movement.',
      source_ids: ['S2', 'S3'],
    },
  ],
  search_tags: ['cobalt-strike', 'beacon', 'post-exploitation', 'source-reviewed'],
  research_route: {
    requested_models: ['google/gemma-4-26b-a4b-it:free'],
    requested_providers: ['google-ai-studio'],
    selected_models: ['google/gemma-4-26b-a4b-it:free'],
    actual_models: ['google/gemma-4-26b-a4b-it:free'],
    providers: ['google-ai-studio'],
    used_fallback: false,
    request_count: 3,
  },
  synthesis_route: {
    requested_models: ['google/gemma-4-26b-a4b-it:free'],
    requested_providers: ['google-ai-studio'],
    selected_models: ['google/gemma-4-26b-a4b-it:free'],
    actual_models: ['google/gemma-4-26b-a4b-it:free'],
    providers: ['google-ai-studio'],
    used_fallback: false,
    request_count: 1,
  },
  evaluation_route: {
    requested_models: ['google/gemma-4-31b-it:free'],
    requested_providers: ['google-ai-studio'],
    selected_models: ['google/gemma-4-31b-it:free'],
    actual_models: ['google/gemma-4-31b-it:free'],
    providers: ['google-ai-studio'],
    used_fallback: false,
    request_count: 8,
  },
  threat_data: {
    profileId: 'sample-cobalt-strike',
    tlpClassification: 'TLP:CLEAR',
    attckSoftwareId: 'S0154',
    claimAttribution: {
      schemaVersion: '2',
      claims: [
        { claimClass: 'threat_activity', claim: 'documents threat actors using Cobalt Strike Beacons for persistence, credential access, lateral movement, and data exfiltration in a wider intrusion chain.', sourceIds: ['S3'] },
        { claimClass: 'forensic_artifact', claim: 'A memory-resident Beacon payload inside an injected process is a forensic artifact analysts can preserve and investigate.', sourceIds: ['S2'] },
        { claimClass: 'detection_indicator', claim: 'Hunt for periodic callbacks to low-reputation infrastructure, accounting for sleep and jitter.', sourceIds: ['S1', 'S2'] },
        { claimClass: 'mitigation_action', claim: 'Enforce least privilege and application control to limit payload execution and lateral movement.', sourceIds: ['S2', 'S3'] },
      ],
    },
  },
};

export const SAMPLE_REPORT_CARD = {
  findings: [
    'Commercial adversary-simulation software whose Beacon payload is also used in real intrusions.',
    'Detection: correlate memory-resident execution, beaconing, credential access, and lateral movement.',
  ],
};
